# Generated by Django 5.2.1 on 2025-05-28 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InsuranceProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("base_premium", models.DecimalField(decimal_places=2, max_digits=12)),
                ("risk_factor", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("economic_factor", models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_number", models.CharField(max_length=50, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("premium", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("canceled", "Canceled"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("client_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.insuranceproduct",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="reports.region"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InsuranceClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claim_number", models.CharField(max_length=50, unique=True)),
                ("event_date", models.DateField()),
                ("report_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                            ("rejected", "Rejected"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "estimated_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("description", models.TextField()),
                ("reserve", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_catastrophic", models.BooleanField(default=False)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="reports.policy"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReserveCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calculation_date", models.DateField()),
                (
                    "total_reserves",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "required_reserves",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "available_reserves",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("stress_scenario", models.CharField(max_length=100)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.insuranceproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("premium", "Premium"),
                            ("claim", "Claim"),
                            ("commission", "Commission"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "expected_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "actual_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("is_recurring", models.BooleanField(default=False)),
                ("forecast_accuracy", models.FloatField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.insuranceproduct",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.policy",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.region",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["date"], name="reports_pay_date_2232c1_idx"),
                    models.Index(
                        fields=["product"], name="reports_pay_product_1374de_idx"
                    ),
                    models.Index(
                        fields=["payment_type"], name="reports_pay_payment_a853c3_idx"
                    ),
                ],
            },
        ),
    ]
